from pathlib import Path
import re,base64,gzip
p=Path('index.html')
src=p.read_text()
m=re.search(r"const parts=\[\s*(.*?)\s*\];",src,re.S)
if not m: raise SystemExit('compressed payload not found')
parts=re.findall(r'`([^`]*)`',m.group(1),re.S)
html=gzip.decompress(base64.b64decode(''.join(parts))).decode()
if 'data-tab="shopping"' not in html:
    html=html.replace('<button class="app-tab active" data-tab="checklist">준비물</button>\n    <button class="app-tab" data-tab="stay">숙소 정보</button>', '<button class="app-tab active" data-tab="checklist">준비물</button>\n    <button class="app-tab" data-tab="shopping">장보기</button>\n    <button class="app-tab" data-tab="stay">숙소 정보</button>')
    panel='''\n  <section id="tab-shopping" class="tab-panel">\n    <section class="card shopping-hero"><div><div class="eyebrow">SHOPPING · YEONGDEOK</div><h2 class="shopping-title">장보기</h2><p class="shopping-desc">현지구매와 인터넷구매 항목을 준비물과 분리해 관리합니다. 체크하면 구매 완료로 저장됩니다.</p></div><button class="btn-primary" onclick="openShoppingModal()">＋ 장보기 추가</button></section>\n    <section class="shopping-summary"><div class="card shopping-stat"><span>전체</span><b id="shop-total">0개</b></div><div class="card shopping-stat"><span>구매완료</span><b id="shop-done">0개</b></div><div class="card shopping-stat"><span>미구매</span><b id="shop-pending">0개</b></div><div class="card shopping-stat"><span>구매예정 금액</span><b id="shop-cost">0원</b></div></section>\n    <div class="shopping-controls card"><div class="filters"><button class="btn-soft shopping-filter active" data-shopping-filter="all">전체</button><button class="btn-soft shopping-filter" data-shopping-filter="local">현지구매</button><button class="btn-soft shopping-filter" data-shopping-filter="internet">인터넷구매</button></div><input id="shoppingSearch" class="search" placeholder="장보기 검색" /></div>\n    <main id="shoppingBoard" class="board shopping-board"></main>\n  </section>\n\n'''
    html=html.replace('  <section id="tab-stay" class="tab-panel">',panel+'  <section id="tab-stay" class="tab-panel">',1)
    css='''.shopping-hero{margin:0 0 14px;padding:22px;display:flex;align-items:center;justify-content:space-between;gap:16px}.shopping-title{margin:0;font-size:30px;letter-spacing:-.04em}.shopping-desc{margin:8px 0 0;color:var(--muted);font-size:14px;line-height:1.55}.shopping-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:14px}.shopping-stat{padding:17px 18px}.shopping-stat span{display:block;font-size:12px;color:var(--muted);font-weight:750;margin-bottom:7px}.shopping-stat b{font-size:22px;letter-spacing:-.04em}.shopping-controls{padding:10px;display:flex;gap:10px;align-items:center;margin-bottom:14px}.shopping-controls .search{margin-left:auto}.shopping-item{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:12px;align-items:center;padding:13px 0;border-top:1px solid var(--line)}.shopping-item:first-child{border-top:0}.shopping-item.done{opacity:.68}.shopping-item.done .shopping-name{text-decoration:line-through;color:#9aa0a8}.shopping-name{font-weight:760}.shopping-meta{font-size:12px;color:var(--muted);margin-top:4px}.shopping-actions{display:flex;gap:7px}.shopping-badge{display:inline-flex;padding:4px 7px;border-radius:999px;background:rgba(10,99,255,.08);color:#0c5ddb;font-size:11px;font-weight:800;margin-left:6px}@media(max-width:760px){.shopping-hero{align-items:flex-start;flex-direction:column}.shopping-summary{grid-template-columns:repeat(2,minmax(0,1fr))}.shopping-controls{align-items:stretch;flex-direction:column}.shopping-controls .search{width:100%;min-width:0;margin-left:0}.shopping-actions{flex-direction:column}}\n'''
    html=html.replace('.note{',css+'.note{',1)
    html=html.replace("  const filtered=items.filter(it=>{\n    if(q&&!it.name.toLowerCase().includes(q)) return false;","  const filtered=items.filter(it=>{\n    if(it.source!=='home') return false;\n    if(q&&!it.name.toLowerCase().includes(q)) return false;",1)
    html=html.replace("if(!board.children.length) board.innerHTML='<div class=\"card empty\">조건에 맞는 준비물이 없습니다.</div>';\n  updateSummary();","if(!board.children.length) board.innerHTML='<div class=\"card empty\">조건에 맞는 준비물이 없습니다.</div>';\n  updateSummary();\n  renderShopping();",1)
    js=r'''let shoppingFilter='all';
function shoppingItems(){return items.filter(x=>x.source==='local'||x.source==='internet')}
function openShoppingModal(id=null){openModal(id);document.getElementById('modalTitle').textContent=id?'장보기 수정':'장보기 추가';if(!id){document.getElementById('fSource').value='local';document.getElementById('fOwner').value=''}}
function renderShopping(){const board=document.getElementById('shoppingBoard');if(!board)return;const q=(document.getElementById('shoppingSearch')?.value||'').trim().toLowerCase();const all=shoppingItems();const list=all.filter(x=>(shoppingFilter==='all'||x.source===shoppingFilter)&&(!q||x.name.toLowerCase().includes(q)));const done=all.filter(x=>x.done).length;const planned=all.filter(x=>!x.done).reduce((s,x)=>s+(Number(x.cost||0)*Number(x.qty||1)),0);const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set('shop-total',all.length+'개');set('shop-done',done+'개');set('shop-pending',(all.length-done)+'개');set('shop-cost',money(planned));board.innerHTML='';if(!list.length){board.innerHTML='<div class="card empty">등록된 장보기 항목이 없습니다.</div>';return}const sec=document.createElement('section');sec.className='card section';const body=document.createElement('div');body.className='section-items';list.forEach(it=>{const row=document.createElement('div');row.className='shopping-item '+(it.done?'done':'');row.innerHTML=`<input aria-label="${it.name} 구매완료" type="checkbox" ${it.done?'checked':''} onchange="toggleDone('${it.id}')"><div><div class="shopping-name">${it.name}<span class="shopping-badge">${sourceLabel(it.source)}</span></div><div class="shopping-meta">${it.category} · 수량 ${it.qty||1}개 · ${money((it.cost||0)*(it.qty||1))}${it.done?' · 구매완료':' · 구매예정'}</div></div><div class="shopping-actions"><button class="save-btn" onclick="openShoppingModal('${it.id}')">수정</button><button class="row-delete-btn" onclick="deleteRowItem('${it.id}')">삭제</button></div>`;body.appendChild(row)});sec.appendChild(body);board.appendChild(sec)}
function initShopping(){document.querySelectorAll('.shopping-filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.shopping-filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');shoppingFilter=btn.dataset.shoppingFilter;renderShopping()}));document.getElementById('shoppingSearch')?.addEventListener('input',renderShopping);renderShopping()}
'''
    html=html.replace('function handleRowSave(id){',js+'\nfunction handleRowSave(id){',1)
    html=html.replace("if(tab.dataset.tab==='report') refreshReport();","if(tab.dataset.tab==='report') refreshReport();\n    if(tab.dataset.tab==='shopping') renderShopping();",1)
    html=html.replace('const STAY_ADDRESS=', 'initShopping();\n\nconst STAY_ADDRESS=',1)
    html=html.replace('#tab-checklist,#tab-stay{display:none!important}','#tab-checklist,#tab-shopping,#tab-stay{display:none!important}')
packed=base64.b64encode(gzip.compress(html.encode(),9)).decode()
chunks=[packed[i:i+7000] for i in range(0,len(packed),7000)]
loader='''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Travelcheck</title></head><body><script>\n(async()=>{try{\nconst parts=[\n'''+',\n'.join('`'+x+'`' for x in chunks)+'''\n];\nconst b64=parts.join('');const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));const ds=new DecompressionStream('gzip');const text=await new Response(new Blob([bytes]).stream().pipeThrough(ds)).text();document.open();document.write(text);document.close();\n}catch(e){document.body.innerHTML='<div style="font-family:-apple-system,sans-serif;padding:40px">Travelcheck를 불러오지 못했습니다.<br><small>'+e+'</small></div>'}})();\n</script></body></html>'''
p.write_text(loader)
print('shopping restored')
